### ISSUE TITLE
game cards don't load if you scroll too fast

### ISSUE THREAD

**Issue by 1ajh** [smartfoloo/arsenic#6]
if you happen to scroll fast enough, some rows of games will not be loaded entirely until you scroll back up at a slower/normal speed

**Comment by smartfoloo** [comment]
i'm honestly not in the mood of updating animations, this could of course be a future update but won't be a top-of-the-priority issue

**Comment by smartfoloo** [comment]
i could fix this issue in a future update, just not my priority right now
