### ISSUE TITLE
blocked by linewize

### ISSUE THREAD

**Issue by 1ajh** [smartfoloo/arsenic#7]
![image](https://github.com/user-attachments/assets/530cbea0-b54e-4f3a-a663-b3a434b3663a)

linewize flags arsenic as malware and blocks it

**Comment by smartfoloo** [comment]
There's no way to get it unblocked...

**Comment by 1ajh** [comment]
maybe try manipulating the metadata, schema, or other aspects?

**Comment by smartfoloo** [comment]
even if i manipulated metadata the site would still be blocked
